### ISSUE TITLE
Published Option Not working

### ISSUE THREAD

**Issue by jlokos** [luciovilla/notion-nextjs-blog#1]
I have attempted to clone the template and for some reason the published option does not work. Whether the box is checked or not the blog post still appears to be rendered.

**Comment by luciovilla** [comment]
Thanks for flagging this @jlokos! I added support for this on my own site but forgot to update it here. Just updated the template to check for the `Published` checkbox ([see logic here](https://github.com/luciovilla/notion-nextjs-blog/blob/main/lib/getNotionData.js#L10-L20)).
