### ISSUE TITLE
Notion: Add a Page/Post Cover image?

### ISSUE THREAD

**Issue by stanleyraywood** [luciovilla/notion-nextjs-blog#2]
_(First thanks for sharing this starter kit)_

Struggling to add a cover image to the blog posts, either in the index or [slug].js file. 
Where would you call this from in your template? I have tried several methods but found only errors.

Appreciate any help here.

**Comment by luciovilla** [comment]
Hey @hellostanley, thanks for using this template. Happy to come up with a solution. Looks like Notion tables have a "Files & Media" property that I could probably use to check if one exists and use that as the cover image.

Let me try this out and will follow up if its working.

**Comment by luciovilla** [comment]
Hey @hellostanley, I just added [support for cover images](https://github.com/luciovilla/notion-nextjs-blog/commit/e169f370dee09d76ba5fca6e1e86562bb2a688ff). You'll see the [sample Notion table](https://vast-rifle-eed.notion.site/8dde3326f8cb4cc68b47a96bea86e9be) now has an extra column with `Cover Image` option where you can either upload an image or add an image URL (both are supported). The image will appear both on the front page river and as the social share image.
